# Generated by Django 2.0.2 on 2018-05-04 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('tag', models.CharField(max_length=20)),
                ('content', models.TextField()),
                ('author', models.CharField(blank=True, max_length=20)),
                ('add_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-add_time'],
            },
        ),
        migrations.AddIndex(
            model_name='blogcontent',
            index=models.Index(fields=['content'], name='vblog_blogc_content_c2da90_idx'),
        ),
    ]
