# Generated by Django 2.0.2 on 2018-05-04 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vblog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcontent',
            name='content',
            field=models.TextField(max_length=2048),
        ),
    ]
