# Generated by Django 2.0.2 on 2018-05-04 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vblog', '0002_auto_20180504_1622'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='blogcontent',
            name='vblog_blogc_content_c2da90_idx',
        ),
        migrations.AddIndex(
            model_name='blogcontent',
            index=models.Index(fields=['content'], name='tb_content_content_79b958_idx'),
        ),
        migrations.AlterModelTable(
            name='blogcontent',
            table='tb_content',
        ),
    ]
